server:
  port: 8001

spring:
  application:
    name: pa-eureka-center
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false
  server:
    enable-self-preservation: false
