server:
  port: 7001

eureka:
  instance:
    hostname: eureka.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false
    service-url:
            # 设置与Eureka交互的地址查询服务和注册服务都需要依赖这个地址
            defaultZone: http://eureka03.com:7003/eureka/,http://eureka02.com:7002/eureka/